# Copyright 2018-2026 the Deno authors. MIT license.

[package]
name = "deno_snapshots"
version = "0.72.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "v8 snapshot used by the Deno CLI"

[lib]
path = "lib.rs"

[features]
default = ["v8_snapshot"]
v8_snapshot = ["deno_runtime/kv", "deno_runtime/napi", "deno_runtime/snapshot", "deno_runtime/telemetry", "deno_runtime/webgpu", "deno_core/v8"]
disable = [
  "deno_core/quickjs",
  "deno_runtime/quickjs",
  "deno_runtime/snapshot_files",
]

[build-dependencies]
deno_runtime = { workspace = true, default-features = false }
deno_core.workspace = true
